name: controlvideo
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - astroid=3.3.11=py310h06a4308_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - dill=0.4.0=py310h06a4308_0
  - expat=2.7.3=h3385a95_0
  - isort=6.1.0=py310h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyhc872135_1
  - platformdirs=4.5.0=py310h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pylint=3.3.8=py310h06a4308_0
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.2.1=py310h06a4308_0
  - tomlkit=0.13.2=py310h06a4308_0
  - typing-extensions=4.15.0=py310h06a4308_0
  - typing_extensions=4.15.0=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.11.0
      - addict==2.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - controlnet-aux==0.0.10
      - decorator==5.2.1
      - decord==0.6.0
      - diffusers==0.35.2
      - easydict==1.13
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - filelock==3.19.1
      - fsspec==2025.9.0
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - jinja2==3.1.6
      - lazy-loader==0.4
      - markdown==3.10
      - markupsafe==2.1.5
      - moviepy==2.2.1
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==2.1.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - positional-encodings==6.0.3
      - proglog==0.1.12
      - protobuf==6.33.0
      - psutil==7.1.3
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scipy==1.15.3
      - sentry-sdk==2.43.0
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.2.0
      - tifffile==2025.5.10
      - timm==1.0.22
      - tokenizers==0.22.1
      - torch==2.8.0
      - torchaudio==2.8.0
      - torchvision==0.23.0
      - tqdm==4.67.1
      - transformers==4.57.1
      - triton==3.4.0
      - typer-slim==0.20.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - wandb==0.22.3
      - wcwidth==0.2.14
      - werkzeug==3.1.3
      - xformers==0.0.32.post2
      - zipp==3.23.0
prefix: /home/roger/miniconda3/envs/controlvideo
